[project]
name = "cryptoget"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.5",
    "django-browser-reload>=1.18.0",
    "django-livereload-server>=0.5.1",
    "sorl-thumbnail>=12.11.0",
]
